name: Run Postman Collection

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  run_postman_collection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run collection.json  # Update the collection.json to match your collection file name
