name: Change Detection

on:
  repository_dispatch:
    types:
      - jira_issue_transition

jobs:
  process-jira-event:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Search for branch and checkout
        id: checkout-branch
        run: |
          ticket_number="${{ github.event.client_payload.issueKey }}"
          if git show-ref --verify --quiet "refs/heads/$ticket_number"; then
            git checkout "$ticket_number"
          else
            echo "Branch $ticket_number not found. Skipping further steps."
            exit 1
          fi

      - name: List modified files
        id: list-files
        run: |
          echo "Successfully checked out branch $ticket_number"
          # Add your commands to list modified files or any other processing here.
