name: Check Branch and Print Dummy Text

on:
  push:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Check if branch exists
        id: check_branch
        run: |
          if git rev-parse --verify --quiet "refs/heads/ticket_number=${{ github.event.client_payload.issueKey }}"; then
            echo "::set-output name=branch_exists::true"
          else
            echo "::set-output name=branch_exists::false"
          fi
      
  print-dummy-text:
    needs: check-branch
    runs-on: ubuntu-latest
    if: ${{ needs.check-branch.outputs.branch_exists == 'true' }}
    steps:
      - name: Print Dummy Text
        run: echo "Dummy text to be printed"
