name: Check JIRA Branch

on:
  push:
    branches:
      - '*'

jobs:
  check_branch:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check if branch exists
      id: check_branch
      run: |
        branch_name=$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')
        if git rev-parse --verify --quiet $branch_name; then
          echo "::set-output name=branch_exists::true"
        else
          echo "::set-output name=branch_exists::false"
        fi
        
    - name: Execute if branch exists
      if: steps.check_branch.outputs.branch_exists == 'true'
      run: echo "Successfully executed"
