name: Change Detection

on:
  repository_dispatch:
    types:
      - jira_issue_transition

jobs:
  process-jira-event:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Search for branch and checkout
        id: checkout-branch
        run: |
          ticket_number="${{ github.event.client_payload.issueKey }}"
          if ! git show-ref --quiet refs/heads/$ticket_number; then
            echo "Branch $ticket_number does not exist. Skipping the rest of the workflow."
            exit 0
          fi

      - name: List modified files
        id: list-files
        if: steps.checkout-branch.outputs.branch_not_found != 'true'
        run: |
          ticket_number="${{ github.event.client_payload.issueKey }}"
          git diff --name-only $ticket_number > modified_files.txt

      - name: Say hello
        run: echo "successfully completed"
