name: Check Branch and Print Dummy Text

on:
  push:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Check if branch exists
        id: check_branch
        run: |
          branch_name=$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')
          if git rev-parse --verify --quiet $branch_name; then
            echo "::set-output name=branch_exists::true"
          else
            echo "::set-output name=branch_exists::false"
          fi
      
  print-dummy-text:
    needs: check-branch
    runs-on: ubuntu-latest
    if: steps.check_branch.outputs.branch_exists == 'true'
    run: echo "Dummy text to be printed"
